# Generated by Django 4.2.6 on 2023-10-28 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0005_remove_booking_club_name_venue_club_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='club_name',
        ),
    ]
