# Generated by Django 4.2.6 on 2023-10-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('club', 'Club')], default='user', max_length=10),
        ),
    ]
