# Generated by Django 4.2.6 on 2023-10-27 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_rename_user_post_nick_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='nick_name',
            new_name='user',
        ),
    ]
