# Generated by Django 4.2.6 on 2023-10-28 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('saved_posts', models.TextField(blank=True)),
                ('registered_events', models.TextField(blank=True)),
            ],
        ),
    ]
